### ISSUE TITLE
Login Database Issue

### ISSUE THREAD

**Issue by Yasak999** [Kaushallrai/Inventory_Management_System#1]
After we successfully connected the database to our login page, the home page didn't show some of the CSS components.

**Comment by uzwa-l** [comment]
> After we successfully connected the database to our login page, the home page didn't show some of the CSS components.

This issue has been solved for this sprint at the last moment, we will improvise it later in another sprint.

**Comment by Kaushallrai** [comment]
To resolve each problem individually, new PHP files were created for login. As a result, all the issues have been successfully addressed.
