### ISSUE TITLE
Add Products Database Issue

### ISSUE THREAD

**Issue by shubhamsd7** [Kaushallrai/Inventory_Management_System#2]

**Comment by Kaushallrai** [comment]
fixed the adding product bug :
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/c3009587-e7ce-4ca9-a3a3-f3838c296384)
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/865e301e-6cbe-4198-b747-a98f37115d10)
