### ISSUE TITLE
user page  cannot add/remove users 

### ISSUE THREAD

**Issue by nishanmajhi** [Kaushallrai/Inventory_Management_System#8]

**Comment by Yasak999** [comment]
I have fixed the add user error and updated the code:

![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/91555207/d4729db9-0904-4030-a8cc-49789f480088)
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/91555207/1a8b3c98-160d-46da-9d60-6a3c891a9712)
![Untitled](https://github.com/Kaushallrai/Inventory_Management_System/assets/91555207/f798d902-a89d-4675-a9b6-33c811e2a5f9)
