### ISSUE TITLE
the image in user page does not load

### ISSUE THREAD

**Issue by nishanmajhi** [Kaushallrai/Inventory_Management_System#9]

**Comment by Yasak999** [comment]
Fixed the image loading bug, the code needed a little fix and I have added it,
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/91555207/e7c71c1d-9b0d-4236-ba3c-e36a39ac4b2f)
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/91555207/e42981bc-bdfb-465d-bfb3-cba01a3035e9)

![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/91555207/d68e6c2b-2e9c-41f1-aeb8-357553fbffe6)
